@baseUrl = http://localhost:9090
@version = v1
@apiUrl = {{baseUrl}}/api/{{version}}

### actuator/health
GET {{baseUrl}}/actuator/health
Accept: application/json

### models/v1
GET {{apiUrl}}/models
Accept: application/json

### models/v2
GET {{baseUrl}}/api/v2.0.0/models
Accept: application/json

### models/v2.0.0
GET {{baseUrl}}/api/v2.0.0/models
Accept: application/json

### models/v2.1.0
GET {{baseUrl}}/api/v2.1.0/models
Accept: application/json

### chat/completions_basic
POST {{apiUrl}}/chat/completions
Content-Type: application/json
Accept: application/json

{
  "model": "ker",
  "messages": [
    {
      "role": "user",
      "content": "1 + 2 = ?"
    }
  ],
  "temperature": 0.7,
  "max_tokens": 100
}

### chat/completions_web-search
POST {{apiUrl}}/chat/completions
Content-Type: application/json
Accept: application/json

{
  "model": "ker",
  "messages": [
    {
      "role": "user",
      "content": "Recherche quel temps fait-il aujourd'hui à Vannes ?"
    }
  ],
  "temperature": 0.7,
  "max_tokens": 100
}

### chat/completions_stream
POST {{apiUrl}}/chat/completions
Content-Type: application/json
Accept: application/json

{
  "model": "ker",
  "messages": [
    {
      "role": "system",
      "content": "You are an code reviewer assistant."
    },
    {
      "role": "user",
      "content": "Java is better than C#, right ?"
    }
  ],
  "temperature": 0.10000000149011612,
  "stream": true,
  "max_tokens": 4096,
  "max_completion_tokens": 8192,
  "frequency_penalty": 0.0,
  "presence_penalty": 0.6
}

### sugar/random
GET {{apiUrl}}/sugar/random?size=10

### sugar/random/window
GET {{apiUrl}}/sugar/randomWindow?size=10&windowSize=2

### sugar/template
GET {{apiUrl}}/sugar/template?name=world

### itinerary/get
GET {{apiUrl}}/itinerary?startAddress=Vannes&endAddress=Paris

### calc/add
GET {{apiUrl}}/calc/add?a=1&b=2

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body === '3', "Result is not 3");
    });
%}
